version: '3'
services:
  service-products:
    image: quarkus/microservices-products-jvm
    container_name: microservice-products
    ports:
      - "8081:8081"
    networks:
      - 03-quarkus-microservices

  service-customers:
    image: quarkus/microservices-customers-jvm
    container_name: microservice-customers
    ports:
      - "8082:8082"
    networks:
      - 03-quarkus-microservices

networks:
  03-quarkus-microservices:
